regexes:
    - "-----BEGIN RSA PRIVATE KEY-----"
    - "-----BEGIN OPENSSH PRIVATE KEY-----"
    - "-----BEGIN PGP PRIVATE KEY BLOCK-----"
    - "[f|F][a|A][c|C][e|E][b|B][o|O][o|O][k|K].*['|\"][0-9a-f]{32}['|\"]"
    - "[t|T][w|W][i|I][t|T][t|T][e|E][r|R].*['|\"][0-9a-zA-Z]{35,44}['|\"]"
    - "[g|G][i|I][t|T][h|H][u|U][b|B].*[['|\"]0-9a-zA-Z]{35,40}['|\"]"
    - "AKIA[0-9A-Z]{16}"
    - "[r|R][e|E][d|D][d|D][i|I][t|T].*['|\"][0-9a-zA-Z]{14}['|\"]"
    - "[h|H][e|E][r|R][o|O][k|K][u|U].*[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}"
    # add your own regex



stopwords:
    - 'setting'
    - 'Setting'
    - 'SETTING'
    - 'info'
    - 'Info'
    - 'INFO'
    - 'env'
    - 'Env'
    - 'ENV'
    - 'environment'
    - 'Environment'
    - 'ENVIRONMENT'
    # add your own stopwords

